BookStackApp/BookStack

- resources/views/users/index.blade.php
> Updated email to be a link

- app/Entity.php
- app/Repos/BookRepo.php
- app/Repos/ChapterRepo.php
- app/Repos/PageRepo.php
Added the ability to search by multi-word terms using double quotes.
> Closes #70.

- .github/ISSUE_TEMPLATE
I would love to help out troubleshooting BookStack issues, but often times there is a clear lack of information available in the bug reports.  Simple things such as PHP and MySQL versions aren't listed which creates noise on the issue for someone to have to ask.  
This is probably by no means "complete" and you should feel free to edit this to include/exclude whatever information you want.
Just trying to help out ❤️
> Added issue template

- resources/assets/js/controllers.js
- resources/assets/js/directives.js
- resources/assets/js/global.js
- resources/assets/js/pages/page-form.js
- resources/assets/sass/_buttons.scss
- resources/assets/sass/_components.scss
- resources/assets/sass/_grid.scss
- resources/assets/sass/styles.scss
- resources/views/books/list-item.blade.php
- resources/views/chapters/list-item.blade.php
- resources/views/pages/edit.blade.php
- resources/views/pages/form.blade.php
- resources/views/pages/list-item.blade.php
- resources/views/partials/entity-selector-popup.blade.php
- resources/views/partials/image-manager.blade.php
> Page link selector

- resources/lang/de/activities.php
- resources/lang/de/auth.php
- resources/lang/de/errors.php
- resources/lang/de/pagination.php
- resources/lang/de/passwords.php
- resources/lang/de/settings.php
- resources/lang/de/validation.php
This translation is based on the current english language files. It is a
transaltion into German (formal) language.  A language selector on the
Settings page would be a nice addition.
> Added initial translation into German (formal)

- app/Providers/AppServiceProvider.php
Synchronize localization for Carbon with main app
> Add Carbon localization support

- resources/assets/js/pages/page-form.js
Uses the browser_spellchecker option documented here - https://www.tinymce.com/docs/configure/spelling/#browser_spellcheck
> Fixes #354, Adds the spellchecker option

- resources/lang/ja/components.php
Added some missing Japanese language for code editor.
Only one file  is modified.
> Japanese lang update

- app/Console/Commands/DeleteUsers.php
- app/User.php
Fixes #579
I've also submitted a patch to update the documentation - https://github.com/BookStackApp/website/pull/16
> Adds code to allow deletion of users via cmd line.

- resources/assets/sass/_components.scss
> Adds font-size to ol to ensure that they are uniform.

- app/Http/Controllers/BookController.php
- app/Repos/EntityRepo.php
- tests/BrowserKitTest.php
- tests/Permissions/RestrictionsTest.php
> Checks the target and the source book before performing the sort.

- resources/lang/it/common.php
- resources/lang/it/entities.php
- resources/lang/it/errors.php
- resources/lang/it/settings.php
Hi, i updated the Italian translation with latest changes
> Update Italian translation

- resources/lang/fr/activities.php
- resources/lang/fr/auth.php
- resources/lang/fr/common.php
- resources/lang/fr/components.php
- resources/lang/fr/settings.php
Updated the french language! What does this mean:
```
==========================
Redundant language content
==========================
fr/settings.php
{
"users_books_view_type": "Disposition d'affichage préférée pour les livres"
}
```
?
> Update french language

- app/Entity.php
- app/Repos/EntityRepo.php
- app/Services/ImageService.php
> PSR2 fixes after running `./vendor/bin/phpcbf`

- resources/lang/de/activities.php
- resources/lang/de/auth.php
- resources/lang/de/common.php
- resources/lang/de/components.php
- resources/lang/de/entities.php
- resources/lang/de/errors.php
- resources/lang/de/settings.php
Added a few missing strings and (hopefully) fixed my borked first commit.
> Update German localization

- resources/lang/sv/components.php
- resources/lang/sv/entities.php
- resources/lang/sv/errors.php
Added some new strings and fixed a couple of typos in the previous translation. 😊
> Updated Swedish translation

- resources/assets/js/services/dates.js
- resources/assets/js/vues/image-manager.js
> Changes the way the date is displayed in image-manager.

- resources/lang/pt_BR/common.php
This pull request adds some missing strings for the pt_BR locale.
> Adds missing pt_BR strings

- resources/lang/de/settings.php
thanks to Levke for helping and laughing
> Update german translation

- resources/lang/de/settings.php
Reverts BookStackApp/BookStack#983
> Revert "Update german translation"

- resources/assets/js/components/markdown-editor.js
> Wrap images inserted with markdown editor with anchor tag to original file

- resources/views/base.blade.php
- resources/views/users/profile.blade.php
1.  Add 3 anchor link to "Created Content" on the "View Profil
e" page and click to jump to the page section
2.  Add "register" to nav.You need to click "login" to find register, which is not convenient for people who are not familiar with the app.
> Add anchor link  on the "View Profile"  & Add "register" to nav.

- resources/lang/es/activities.php
- resources/lang/es/auth.php
- resources/lang/es/common.php
- resources/lang/es/components.php
- resources/lang/es/entities.php
- resources/lang/es/errors.php
- resources/lang/es/pagination.php
- resources/lang/es/passwords.php
- resources/lang/es/settings.php
- resources/lang/es/validation.php
> Spanish update

- resources/lang/de/entities.php
- resources/lang/de_informal/entities.php
This PR should add the necessary german translations for shelves. If there are other translation keys missing, please let me know.
> Add german translations for shelves

- resources/lang/sv/auth.php
- resources/lang/sv/common.php
- resources/lang/sv/entities.php
- resources/lang/sv/settings.php
- resources/lang/sv/validation.php
An even newer update of the Swedish language files
> Updated the Swedish language files

- resources/lang/pt_BR/activities.php
- resources/lang/pt_BR/auth.php
- resources/lang/pt_BR/common.php
- resources/lang/pt_BR/components.php
- resources/lang/pt_BR/entities.php
- resources/lang/pt_BR/errors.php
- resources/lang/pt_BR/pagination.php
- resources/lang/pt_BR/passwords.php
- resources/lang/pt_BR/settings.php
- resources/lang/pt_BR/validation.php
As stated in the Upgrade Notes of version 0.26.0:
> Translations - Since many interfaces and lines of text have been updated, It may take a little while for some translations to catch-up. Expect to see more English text than usual if you're using a non-English language option.
This pull request fixes the pt_BR translation strings.
> Fix pt_BR translations

- resources/lang/de/activities.php
- resources/lang/de/auth.php
- resources/lang/de/common.php
- resources/lang/de/entities.php
- resources/lang/de/errors.php
- resources/lang/de/settings.php
- resources/lang/de/validation.php
I went through all (formal) german translation files - using the lang/check.php tool - and tried to fill in all missing translations and deleted the redundant ones.
> German translation extended

- resources/views/auth/forms/login/standard.blade.php
- resources/views/form/text.blade.php
Adds autofocus on the email field of the standard login page.
> Adds autofocus on the email field of the standard login page.

- app/Http/Controllers/SettingController.php
- app/Notifications/TestEmail.php
- resources/lang/en/settings.php
- resources/views/settings/maintenance.blade.php
- routes/web.php
> Add feature to send test e-mails

- app/Http/Controllers/Auth/LoginController.php
> Bugfix - download and assign avatar when creating LDAP user in database

- app/Config/setting-defaults.php
- resources/js/components/index.js
- resources/js/components/setting-app-color-picker.js
- resources/js/components/setting-color-picker.js
- resources/lang/en/settings.php
- resources/views/partials/custom-styles.blade.php
- resources/views/settings/index.blade.php
This is a placeholder to address #1380 creating a UI and storing settings for the css color variables for page, page draft, chapter, book, and shelf.
> Customize colors in settings

- app/Http/Controllers/BookshelfController.php
> Fix for missing cover on create new shelf

- resources/js/services/code.js
- resources/views/components/code-editor.blade.php
> Added support for Fortran language

- resources/views/common/header.blade.php
Removed extra spaces displayed in the header of the login and registration link.
> Updated login and registration header actions to be consistent with other header links

- resources/js/components/dropdown.js
- resources/lang/en/settings.php
- resources/sass/_blocks.scss
- resources/sass/_buttons.scss
- resources/sass/_components.scss
- resources/sass/_forms.scss
- resources/sass/_header.scss
- resources/sass/_layout.scss
- resources/sass/_lists.scss
- resources/sass/_mixins.scss
- resources/sass/_pages.scss
- resources/sass/_spacing.scss
- resources/sass/_tables.scss
- resources/sass/_text.scss
- resources/sass/print-styles.scss
- resources/sass/styles.scss
- resources/views/auth/forms/login/saml2.blade.php
- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
- resources/views/base.blade.php
- tests/LanguageTest.php
- Intended to improve RTL support in the interface.
- Also adds hebrew to language dropdown since that was missing.
Related to #1794
> Updated styles to use logical properties/values, for improved RTL support

- app/Http/Controllers/Api/BookshelfApiController.php
- public/.htaccess
- routes/api.php
API Authorization problem on my laragon server. I have fixed it by copy and past Handle Authorization Header from this https://github.com/laravel/laravel/blob/master/public/.htaccess. 
thanks
> Added Handle Authorization Header on .htaccess and added a base Shelf API implementation

- .env.example.complete
- app/Actions/ActivityService.php
- app/Config/logging.php
- app/Http/Controllers/Auth/LoginController.php
Hi,
This PR logs failed login attempts for further processing by tools such as fail2ban.
It then closes #728.
Thank you 👍
> Log failed accesses

- .github/workflows/test-migrations.yml
This PR adds a workflow to automatically test migrations
> Add `test-migrations` workflow

- resources/js/services/code.js
- resources/views/components/code-editor.blade.php
Addition of VBScript Codemirror following the request #2255
> Add VBScript Codemirror

- app/Auth/Permissions/PermissionService.php
- app/Http/Controllers/Images/ImageController.php
- composer.json
- tests/Permissions/RestrictionsTest.php
- tests/User/UserApiTokenTest.php
- tests/User/UserPreferencesTest.php
- tests/User/UserProfileTest.php
This PR adds some fixes discovered and applied by laravel-microscope package.
> Fixes from laravel-microscope package

- app/Entities/Repos/PageRepo.php
- resources/lang/en/entities.php
I made this in support of my request in #2349
> Automatic Restored Revision Changelog Summary Text

- resources/lang/es/auth.php
> Fixed user invite email subject in spanish translation (#2608)

- app/Auth/Access/SocialAuthService.php
- app/Auth/User.php
- app/Auth/UserRepo.php
- app/Entities/Models/Entity.php
- app/Entities/Tools/SearchRunner.php
- app/Entities/Tools/SlugGenerator.php
- app/Http/Controllers/Auth/SocialController.php
- app/Http/Controllers/SearchController.php
- app/Http/Controllers/UserController.php
- app/Http/Controllers/UserProfileController.php
- app/Interfaces/Sluggable.php
- database/factories/ModelFactory.php
- database/migrations/2021_03_08_215138_add_user_slug.php
- resources/views/common/header.blade.php
- routes/web.php
- tests/Auth/AuthTest.php
- tests/Entity/EntitySearchTest.php
- tests/User/UserProfileTest.php
> User slugs

- app/Entities/Tools/SearchRunner.php
- resources/lang/en/entities.php
- resources/views/search/all.blade.php
- tests/Entity/EntitySearchTest.php
This adds the feature to search entities by owner to resolve #2529.
> Search owned by me

- app/Entities/Models/Bookshelf.php
- app/Http/Controllers/BookshelfController.php
- app/Http/Controllers/UserController.php
- resources/views/shelves/show.blade.php
Hello,
as referred in the issue #1742 , I've added the possibility to sort books within shelves.
Please give me your feedback
> Sort Books within Shelves

- app/Actions/ActivityService.php
- database/migrations/2021_08_21_044614_add_column_ip_into_activities.php
- resources/lang/en/settings.php
- resources/views/settings/audit.blade.php
IP is now saved into audit log. exist records without IP will shown as blank.
> Log ip address

- .env.example
- .env.example.complete
- app/Auth/Permissions/PermissionService.php
- app/Config/database.php
> Allow to use DB tables prefix

- app/Entities/Tools/PageContent.php
- tests/Entity/PageContentTest.php
See https://github.com/BookStackApp/BookStack/issues/3058 for informations
> feat(PageContent): set unique ids on nested headers

- app/Http/Controllers/Auth/MfaBackupCodesController.php
- app/Http/Controllers/Auth/MfaController.php
- app/Http/Controllers/Auth/MfaTotpController.php
- app/Http/Controllers/FavouriteController.php
- app/Http/Controllers/PageController.php
- app/Http/Controllers/RoleController.php
- app/Http/Controllers/TagController.php
- app/Http/Controllers/UserProfileController.php
- app/Http/Controllers/WebhookController.php
Many pages were missing their unique tab/page titles
so this change is just to distribute them back over
many common areas where they were missing.
> Added page titles to many missing app areas

- app/Http/Controllers/UserController.php
- tests/User/UserManagementTest.php
See https://github.com/BookStackApp/BookStack/issues/3174
What this PR do:
- Wrap the user creation process in a transaction
- Add test
> When creating a user, do not persist the user on invitation sending failure
