.env.example
config/cache.php

I exposed a one Memcached server configuration through the .env file.  If somebody needs more than one Memcached server configured, they'll have to add them to `config/cache.php` which isn't super ideal.  Open to other ideas if need be.

Closes #69.  Implemented and tested memcached.

---

database/migrations/2015_07_12_114933_create_books_table.php
database/migrations/2015_07_12_190027_create_pages_table.php
database/migrations/2015_07_27_172342_create_chapters_table.php

This will help fix the bug where some people get the message FULLTEXT is not supported. until mysql 5.6 innodb does not support FULLTEXT by using MyISAM for the tables that require FULLTEXT this issue will be fixt. (This will only work for new installations because you can't change the type after a table is created.

Making sure MyISAM is set

---

app/Http/Middleware/Authenticate.php

If not logged in, it redirects to login form (previously without baseUrl).
As discussed on https://github.com/ssddanbrown/BookStack/issues/40#issuecomment-239105837 there may be some left over instances of this

Applied baseUrl to login redirect

---

app/Http/Controllers/PageController.php
app/PageRevision.php
composer.json
composer.lock
resources/assets/sass/_pages.scss
resources/views/pages/page-display.blade.php

html diff in revision view

---

app/Services/Ldap.php

This is a very crude workaround to allow LDAPS connections. A better solution would be the one explained in the comments.

Update Ldap.php to allow LDAP over SSL/TLS connections

---

app/Notifications/ConfirmEmail.php

Implements Laravel's queue abilities into the email notification job. Should not affect existing installations that are not using queues as the environment file defaults to `sync`.

Queue confirmation emails.

---

.travis.yml
resources/views/books/show.blade.php
resources/views/chapters/show.blade.php
tests/Auth/LdapTest.php

Avoid ignoring new lines when renderring the book/chapter descriptions on their respective detailed views.
And fixing the tests too (LDAP needs to be installed before running the LDAP tests).

Support new lines for book/chapter descriptions + fix tests

---

app/Repos/EntityRepo.php

Generate russian slug not correct if using strtolower.
Better using mb_strtolower if that function exists.

Russian slug  and Multibyte String

---

resources/views/pages/form-toolbox.blade.php

Fixes #513. Tag suggest URLs were hardcoded to /ajax in blade template. Wrapped them in baseUrl()

Fix ajax tag suggestion for subdir installs

---

app/Http/Controllers/ImageController.php
app/Repos/ImageRepo.php
app/Services/AttachmentService.php
app/Services/ImageService.php
app/Services/UploadService.php
config/filesystems.php
routes/web.php
storage/uploads/images/.gitignore

This feature puts images behind the authentication barrier so they are only viewable by logged-in users. Permission levels not taken into account, It's simply based on 'Is user authed?'.
Cannot be used alongside public viewing.
Set to be opt-in for now.
Public image access should still be served by the webserver as before, Secure image access goes through the app so will have a performance penalty.
Still in testing. Would be great for folks to test on their setups for any issues. (Do not test on production instances though). I experienced issues doing something similar when initially creating BookStack but so far everything has been working without issue on my dev machine.
To use simply set `STORAGE_TYPE=local_secure` in your `.env` file.
Files will be stored in a `storage/uploads/images` …

Adds ability to secure images behind auth

---

resources/assets/sass/_components.scss
resources/views/components/code-editor.blade.php

Towards #650
Although adding a scroll-bar to the modal although is a fairly simple solution, it causes two scroll-bars to appear on the popup if the content in the code editor is more.
@ssddanbrown - Any ideas?

Adds overflow:auto to popup content to allow it to scroll in lower res.

---

.env.example

.env.example had wrong keys for okta from the original PR which where changed in ```config/services.php?```
This PR changes these keys in .env.example to the ones uses in config/services.php to match other auth services.

Corrected the keys for okta auth

---

resources/views/search/all.blade.php

**Added Search Permission for not logged in Users**
When before user logged in, if user try to search something, in options tag there is a personalized checkboxes.
I Removed it by adding simple condition.

Added Search Permission for not logged in Users

---

.env.example

We had some problems with multiple BookStack instances using the same caching server. Perhaps it's a good idea to have this available in the `.env.example` file.

Add CACHE_PREFIX to the .env.example file

---

resources/assets/sass/_forms.scss

This fixes #715 when I apply the change in my browser.

fix markdown editor resizing with long strings

---

app/Services/ImageService.php
resources/assets/js/vues/components/dropzone.js

Close #223 
Also fixes issues with improper error message when file is too large.

Fixes issues with gif images not animating

---

resources/assets/js/vues/attachment-manager.js
resources/views/pages/form-toolbox.blade.php

Fixes #884
This is happening because -
> Due to the limitations of modern JavaScript (and the abandonment of Object.observe), Vue cannot detect property addition or deletion. Since Vue performs the getter/setter conversion process during instance initialization, a property must be present in the data object in order for Vue to convert it and make it reactive.
Source: https://vuejs.org/v2/guide/reactivity.html
Also added padding to the icons in the attachment section.
**Before**
**After**

Fixes issue with having to click the delete icon for attachment twice.

---

resources/assets/js/components/page-display.js

Fixes #873
Note that this does not need to be a hotfix because the navigation functionality still works, just the smooth scrolling effect has an issue.

Fixes undefined error when clicking on link under page navigation.

---

resources/assets/sass/_pages.scss
resources/views/pages/revision.blade.php

Closes #888
See image below,
Also tested PDF export and HTML export. The same CSS are applied to the `pre code` section but Dompdf does not seem to support `white-space: pre-wrap` whereas wkhtmltopdf does.
- wkhtmltopdf - [test-page-wkhtmltopdf.pdf](https://github.com/BookStackApp/BookStack/files/2151410/test-page-wkhtmltopdf.pdf)
- Dompdf - [test-page-dom-pdf.pdf](https://github.com/BookStackApp/BookStack/files/2151411/test-page-dom-pdf.pdf)

Fixes issue with code not wrapping on revision page.

---

.env.example
app/Http/Controllers/Auth/LoginController.php
app/Repos/LdapRepo.php
app/Services/LdapService.php
config/services.php

Closes issue #75 
I set it up so that when users login using an LDAP connection, Bookstack will get all names of all groups that user is a part of on the LDAP server, and will try and match them to the names of roles created in Bookstack. For any matches it finds, it will add the user to that role on Bookstack. The groups to roles sync function only runs on login, so if a user's groups change on the LDAP server, they need to log out of Bookstack, and log back in for any changes to roles to take affect.
You do need to create roles on Bookstack with names that match groups on LDAP exactly for this to work. I did contemplate having Bookstack create roles on a LDAP login for all groups it found for a user, but talking to a few network admins, most applications have the app admins create the …

#75 - LDAP user groups sync to Bookstack on Login

---

app/Repos/UserRepo.php
app/Services/SocialAuthService.php
resources/lang/en/settings.php
resources/views/settings/index.blade.php

Related to #574 
I added a setting to allow auto silent registration of user when social auth is used.
Few things to be aware of:
- enabling this setting would disable email verification for social auth but it's described under the setting + I think email verification for social auth is useless.
- if domain restriction is enabled => the auto social registration process respect it.
Missing: translation & probably better wording (my english is not perfect)
Missing: check of wording + translations

implement social auto registration feature

---

resources/lang/pt_BR/activities.php
resources/lang/pt_BR/common.php
resources/lang/pt_BR/entities.php
resources/lang/pt_BR/errors.php
resources/lang/pt_BR/settings.php

After update 0.24, several strings referencing the bookshelves feature were added, causing a lack of translation when the pt_BR locale is used. This pull request adds these missing strings.

Adds missing pt_BR translation

---

resources/assets/js/vues/image-manager.js

Fixes #1092
I was unable to test it on a sub-directory, since while setting up was getting an issue stating - 
```
[Sun Nov 25 00:14:25.175814 2018] [core:error] [pid 30398] [client ::1:50186] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
```
But I'm fairly certain that this will fix the issue. Tested on the PHP localhost server.

Fixes image deletion failing in subdirectory.

---

config/app.php
resources/lang/de_informal/activities.php
resources/lang/de_informal/auth.php
resources/lang/de_informal/common.php
resources/lang/de_informal/components.php
resources/lang/de_informal/entities.php
resources/lang/de_informal/errors.php
resources/lang/de_informal/pagination.php
resources/lang/de_informal/passwords.php
resources/lang/de_informal/settings.php
resources/lang/de_informal/validation.php
resources/lang/en/settings.php

This commit adds German informal language ("Du" instead of "Sie") based on the current formal language files. Fixes this part of #890.

add German informal language

---

.env.example
app/Auth/Access/LdapService.php
config/services.php

This PR allows users to set `LDAP_TLS_INSECURE` in their `.env` to bypass LDAP TLS Certificate Verification. This is useful for development environments that may not have a trusted CA certificate for LDAP functionality.

Add option to disable LDAPS Certificate Validation

---

.env.example
.env.example.complete
config/app.php
config/session.php

Cleanup of the `.env.example` since it was getting messy.
This simplifies the file to only show what's fully needed.
A `.env.example.complete` contains all possible options with comments for each.
Will need to review docs to see where variables are mentioned as may have to change wording from `set` to `add` in some areas where old variables have been removed.

Simplified example env and created full example copy

---

resources/views/components/code-editor.blade.php

Adds a Powershell link to the Code Editor component to utilize the syntax highlighting already built in by codemirror.
Closes #1040

Add Powershell Code Markup

---

resources/lang/nl/auth.php

At the moment the Dutch translation says ```Minimaal 5 tekens``` which means your password should be at least 5 characters long. But a 5 character long password is not allowed by the validator. 
I think this was a translation error from the English one where it says ```Must be over 5 characters```. To make the Dutch translation correct the Dutch translation should be changed to ```Minimaal 6 tekens```.
```
/**
* Get a validator for an incoming registration request.
*
* @param  array $data
* @return \Illuminate\Contracts\Validation\Validator
*/
protected function validator(array $data)
{
return Validator::make($data, [
'name' => 'required|max:255',
'email' => 'required|email|max:255|unique:users',
'password' => 'required|min:6',
]);
}
```

Update Dutch password_hint translation to correspond with validation

---

resources/assets/sass/_components.scss
resources/lang/en/validation.php

Fixes #1186
---
1. I've added a message.
2. The tooltip arrow now appears slightly off-center. I think that's an acceptable trade-off.

Fixes tooltip on the image manager.

---

app/Auth/Permissions/PermissionService.php
app/Http/Controllers/BookController.php
resources/views/books/create.blade.php
resources/views/shelves/show.blade.php
routes/web.php
tests/Entity/BookShelfTest.php

A solution for #1260 .
Some notes:
- When a book is added, it is added to the top of the shelf. 
- When a book is added, you get redirected back to the shelf rather than the new book. This works for me, but may not work for the majority.

Add a 'Create New Book' button on shelf list

---

resources/views/form/role-checkboxes.blade.php

Fix for #1325 
Dot notation handling in laravel means it was looking for the existence of a value in the wrong place.
Eg, if the role name was `a.role.name` it would look in `roles['a']['role']['name']` instead of `roles['a.role.name']`
I couldn't find anywhere where the name of the role is used in setting roles (they are set with IDs), so changing the dots in the form elements name attribute to something else seems to have fixed this without any unintended side effects.
Could be an issue if someone had a role called `a.role` and a second role called `aDOTrole`, but I can't see this being the case for too many users.
Edit: I should note that the display name of the role isn't changed, so it will still appear in the form with dots.

Replace dots with something else on user create and edit screens

---

app/Http/Controllers/Auth/RegisterController.php
resources/views/auth/forms/login/standard.blade.php
resources/views/auth/login.blade.php
resources/views/common/header.blade.php
tests/Auth/AuthTest.php

I think people expect to find a sign up link close to the login form, so added one next to forgot password if registration is enabled. Also fixed #1239 while I was there.
Hope this helps.

Add sign up link to login screen and fix registration form validation

---

resources/assets/js/components/entity-permissions-editor.js
resources/assets/js/components/index.js
resources/views/form/entity-permissions.blade.php

I just spent too much time figuring out why my custom permissions were not working. Turned out I didn't enable them.
This PR hides the permissions table unless you enable custom permissions. That should save some time and frustration for users who apparently cannot read (like me :smile:).

Hide permissions table unless custom permissions are enabled

---

resources/lang/en/settings.php

fix en file to read:
> Disconnecting an account here does not **revoke** previously authorized access

Fix missing word in users_social_accounts_info string

---

app/Http/Middleware/Localization.php
resources/views/base.blade.php
resources/views/books/export.blade.php
resources/views/chapters/export.blade.php
resources/views/pages/export.blade.php
resources/views/vendor/notifications/email.blade.php

Added top level flags to allow browsers to render locale specific features correctly

Added locale and text direction to html templates

---

dev/docker/Dockerfile

**Describe the bug**
Can not run `composer install` inside `app` docker container. The error appears because `Composer` can not find `git`. 
**Steps To Reproduce**
Steps to reproduce the behavior:
The same steps explained in the `README` file.
1. Clone master branch.
2. Run the command: `docker-compose run app composer install`.
3. The error appears as the image in screenshots.
**Expected behavior**
Installing Packages inside Docker container.
**Screenshots**
Tested on my local machine and on a Digitalocean droplet.
**My Configuration:**
- Exact BookStack Version: The version of `master` branch.
- PHP Version: 7.3
- Hosting Method (Nginx/Apache/Docker): Docker.
This pull request adding git to the docker image. So Composer can install packages without the `git` error.

Fixing composer install inside docker `app` container

---

resources/views/settings/maintenance.blade.php

* Added a link to the Github releases page when someone clicks the current release version (to look for changelog information, or to see if there are new updates)
* Removed unnecessary BR tag by fixing the CSS class for the version display so it is properly aligned with the rest of the menu

Update maintenance.php to link to Github release page & minor style tweak

---

app/Config/app.php
app/Providers/TranslationServiceProvider.php
app/Translation/FileLoader.php
tests/ThemeTest.php

Related to #406, Although does not close it outright.
This pull request adds the ability to override existing text translation content with custom values via the theme system (#652).
1. Create a custom theme folder within the existing `themes/` directory.
- For example `themes/awesome_theme`
2. Within your `.env` folder set a `APP_THEME` variable with the value matching your custom theme folder name.
- For example `APP_THEME=awesome_theme`
3. Add some language content within your theme folder within a `lang` folder.
- This folder mirrors the default structure of the BookStack `resources/lang/` folder.
- For example, I can create `themes/awesome_theme/lang/en/entities.php`, Adding in the content below:
```php
<?php
return [
'books' => 'Sandwiches',
];
```
4. The new translations will now …

Add ability to override translations with custom text

---

resources/views/books/form.blade.php
tests/Entity/EntityTest.php

Fixes #1662
Added a small block of logic to determine the correct URL to attribute to the cancel button on a given page create form.
If adding a book from a bookshelf, return to the bookshelf. If editing a book, return to the book. In all other cases, return to the full books list.

Fix Book form (create) returning to the full books list on cancel

---

app/Entities/Repos/BaseRepo.php

When creating or updating a bookshelf, the provided cover was not assigned.

Bugfix - Bookshelf cover was not assigned

---

app/Entities/Repos/PageRepo.php

Currently, when you move a page, you get a list of Books and chapters. Unfortunately, if you choose a chapter as new destination for a page, you get an error, since currently only books as target are supported.
This PR allows you to move a page directly into a chapter by checking, if the parent is a Chapter. If so, the page will be assigned to the target chapter and moved to the corresponding book.

Feature: Move a page directly into a chapter of another book

---

app/Auth/Access/ExternalAuthService.php
app/Auth/Access/LdapService.php
app/Auth/Access/Saml2Service.php
app/Config/app.php
app/Config/saml2_settings.php
app/Config/services.php
app/Exceptions/SamlException.php
app/Http/Controllers/Auth/LoginController.php
app/Http/Kernel.php
app/Listeners/Saml2LoginEventListener.php
app/Providers/EventServiceProvider.php
composer.json
composer.lock
resources/lang/de/errors.php
resources/lang/de_informal/errors.php
resources/lang/en/errors.php
resources/views/auth/login.blade.php
resources/views/settings/roles/form.blade.php
resources/views/users/form.blade.php

This PR should be the base of adding SAML as an additional authentication provider for bookstack accounts. Currently with some minimal configuration in `.env` as specified below, the use should be redirected to the configured identity provide and redirected back to the application. The actual handling of the logged in event remains to be done, as the data sent to the IDP is still somehow broken. Hence the WIP for this PR.
```
SAML2_ENABLED=true
SAML2_IDP_SSO=https://example.com/idp/SSORedirectLogin
SAML2_IDP_x509=BASE64IDPCERT==
SAML2_IDP_ENTITYID=https://example.com/idp/metadata.xml
```

SAML Auth Provider

---

app/Http/Middleware/TrustProxies.php

Fix an exception error 
```
ErrorException
Declaration of BookStack\Http\Middleware\TrustProxies::handle($request, Closure $next) should be compatible with Fideloper\Proxy\TrustProxies::handle(Illuminate\Http\Request $request, Closure $next) 
```

Fix An Exception 

---

resources/sass/_components.scss
resources/views/partials/notifications.blade.php

In relation to #1525
This adds a simple close icon to all notification panes. Here is an example of how it looks:
Per the comments on the bottom of the issue thread, it doesn't actually do anything, besides provide the user a visual cue reminding users to click to dismiss the notification.

Add close icon to notifications

---

resources/js/services/code.js
resources/views/components/code-editor.blade.php

As it says. There's a lot of legacy Perl scripts going around. Just the kind of stuff you'd like to document in a wiki.

Add Perl syntax highlighting to code editor

---

app/Auth/Access/SocialAuthService.php

Azure Conditional Access policy 2FA returns 'interaction_required' 400 response and therefor breaks authentication when forced to use 2FA. 
https://github.com/SocialiteProviders/Providers/issues/208

Fixed 'interaction_required' response for azure

---

resources/views/components/setting-entity-color-picker.blade.php

Reducing indentation to one look in the application settings.

Removed spacing in color picker actions to account for languages with longer text

---

app/Http/Controllers/BookController.php
app/Http/Controllers/BookshelfController.php
app/Http/Controllers/Images/GalleryImageController.php
app/Http/Controllers/SettingController.php
app/Http/Controllers/UserController.php
app/Uploads/ImageRepo.php

Validation fixes

---

app/Http/Controllers/Auth/LoginController.php
resources/views/common/header.blade.php

Currently, for a non-public BookStack instance, the [Authenticate Middleware](https://github.com/BookStackApp/BookStack/blob/02af69ddf29e0a2d03cc3a8660bfca9a65175afc/app/Http/Middleware/Authenticate.php#L44) sets the `url.intended` session key when accessing any link while not logged in, which tells the [login procedure](https://github.com/BookStackApp/BookStack/blob/02af69ddf29e0a2d03cc3a8660bfca9a65175afc/app/Http/Controllers/Auth/LoginController.php#L110) to redirect there after login.
A public BookStack instance will not exhibit this behavior for pages which require additional permissions, as a common 404 is returned (which is the correct thing to do). With these changes, the view at `/login` recognizes an optional query parameter `intended` and sets the intended redirect URL when …

Recall intended route when manually clicking login

---

resources/sass/_text.scss

Optionally we could consider removing the rule at line 274. This doesn't handle multiple layers of nested lists and would be better covered by the generic rule which checks for an `ol` or `ul` nested inside a `li` which is how MarkDown renders nested lists as HTML.
**Issue Link:** #1911

Resolve issue #1911 (Additional margin/padding present in nested lists)

---

app/Entities/Repos/EntityRepo.php
app/Http/Controllers/BookController.php
resources/lang/en/entities.php
resources/views/books/show.blade.php
tests/Entity/BookShelfTest.php

Closes #1598
I put these underneath actions because there could potentially be many that push the actions off-screen. But you will likely want to change the placement of this if this is a feature you wish to merge 👍 
Another part of this PR to look out for is the heading above the list. I went with Bookshelves because I think it should be clear enough from the context (a book) that it is referring to the bookshelves that the book can be found on.
Thanks

Show list of bookshelves that a book belongs to on a book view

---

app/Http/Controllers/BookshelfController.php
resources/views/shelves/show.blade.php

This PR adds the list/grid view toggle button to the shelves.show view. This button is already available in the shelves.index as well as in books.index.
This allows users to use the desired view even when looking directly into a shelf.

Feature - allow toggling between grid and list view in shelf view (shelves.show)

---

package-lock.json
package.json
resources/sass/_spacing.scss

This PR replaces `node-sass` with `sass`. `sass` is the [SASS/SCSS reference implementation](https://github.com/sass/dart-sass).
- No native dependencies (JS only)
- Faster availability of new features
- A bit slower, but not very noticable.
`node-sass` broke again for me with Node 14 with some error that it couldn't download some binaries from GitHub.
```
node_1     | Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-83_binding.node
node_1     | Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-83_binding.node": 
node_1     | 
node_1     | HTTP error 404 Not Found
node_1     | 
node_1     | Hint: If github.com is not accessible in your location
node_1     |       try setting a proxy via HTTP_PROXY, …
```

Replace node-sass with dart-sass

---

app/Entities/SlugGenerator.php
tests/Entity/EntityTest.php

Added Illuminate\Support\Str::slug to generate slug from text to improve the creation of slugs with non-English characters.
Fix issue #2026 
**before:**
```
name = "¿ De qué color son los paños calientes ?"
slug  = "¿-de-qué-color-son-los-paños-calientes-"
encoded_slug = "%C2%BF-de-qu%C3%A9-color-son-los-pa%C3%B1os-calientes-"
```
```
name = "основная-информация"
slug="основная-информация"
encoded_url = "%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0%D1%8F-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F"
```
**After ( with Str::slug() )**
```
name = "¿ De qué color son los paños calientes ?"
slug  = "de-que-color-son-los-panos-calientes"
encoded_slug = "de-que-color-son-los-panos-calientes"
```
```
name = "основная-информация"
slug="osnovnaya-informatsiya"
encoded_slug = …
```

Use Str::slug to create slugs from string #2026

---

app/Entities/Managers/PageContent.php

Decode HTML entities in the text content before returning an excerpt.  Fixes #2114.

Decode HTML entities in excerpts

---

resources/sass/_variables.scss

`$mono` CSS variable had misspelling of `Ubuntu Mono`.

Fixed "Ubunto Mono" $mono type misspelling

---

database/migrations/2020_09_19_094251_add_activity_indexes.php

This PR fixes `artisan migration:rollback`, which was broken due to incorrect index names in the `2020_09_19_094251_add_activity_indexes` migration:
```
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP INDEX `key`; check that it exists (SQL: alter table `activities` drop index `key`)
```

Fix the `AddActivityIndexes` migration's `down()` method

---

resources/sass/_blocks.scss

Updated callout links to use font colouring based on type, with bold text to denote link, instead of using the theme link colour. Closes #303.
SCSS has been updated, will need CSS (npm run dev) before merge.

Updated callout link formatting

---

app/Entities/Managers/BookContents.php

Currently, if I create a page with included content (`{{@123}}`) then I see the rendered content when I export the page or its containing chapter.  But the book export prints the literal string `{{@123}}` in the output instead of the included content.
This change results in the included content being rendered no matter which object (book, chapter, page) is exported.
Fixes #2228

Render included content when exporting books

---

public/.htaccess

If BookStack instance is deployed to any non-root path, e.g. `http://example.com/wiki/`,
requests for `http://example.com/wiki/shelves/`
was redirected to `http://example.com/shelves`
instead of `http://example.com/wiki/shelves`.
`%{REQUEST_URI}` contains whole URL path, script path included.

Fixed canonical redirects on non-root url app instances

---

dev/docker/entrypoint.node.sh
package.json

This PR adds the `--initial` flag to `chokidar`. This ensures that the JS resources get built immediately after starting the `build:js:watch` script. I also passed the `SHELL` environment variable down to node in the node entrypoint because `chokidar` does not run without it.
tl;dr: this makes it possible again to clone the repository, follow the Docker steps in the README and having a working dev installation after that :)

Fix build:js:watch not building at first launch in Docker

---

dev/docker/entrypoint.app.sh
readme.md

I think it is an unnecessary step to install composer dependencies manually when using the Docker development environment. NPM dependencies also get installed automatically so this is just one less thing to think of :)
I also noted that you need to set `APP_ENV` to `local` because database migrations won't run otherwise. (Command is skipped in production)

Install composer dependencies in Docker entrypoint

---

resources/sass/_layout.scss

There is issue with viewing all the export list.
Step to reproduce the issue:
1. Login to bookstack.
2. Open any book or page.
3. Click on export.
4. There are three list in the dropdown but only two can be visible third one is hidden.

Fix issue with viewing export dropdown list

---

resources/views/common/home-book.blade.php
resources/views/common/home-shelves.blade.php

This PR adds the "Create Shelf" button to the Shelves-Homepage and "Create Book" button to the Books-Homepage definied in the settings menu.
Assume you've set the homepage to "shelves". With this PR, there is no need to click on "Shelves" in the top menu first (which is for the user basically the same view) in order to create a shelf.
In our case, some users were confused why they were not allowed to create a shelf even if they had the permission. This was only caused by the missing button in the home view.

Feature - add the "Create Shelf" resp. "Create Book" to the home view

---

resources/views/form/password.blade.php
resources/views/users/form.blade.php

This seems to catch people up on my instances a lot, since you can't upload a new profile picture with the change password fields filled in.

Disable autocomplete on the change password field

---

docker-compose.yml

See: https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
Fixes the following error:
glob error:
[Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
errno: -13,
code: 'EACCES',
syscall: 'scandir',
path: '/root/.npm/_logs'
}

Docker: Fix permission with node service by adding node as user

---

.env.example.complete
app/Config/setting-defaults.php

Thanks @ssddanbrown for explaining the relationships. Here is a PR that allows the missing configuration via the .env file.
Best,
philjak

Adding APP_VIEWS_BOOKSHELF to .ENV

---

.env.example.complete
app/Config/session.php

The session cookie path parameter can not configured by an env file. There are scenarios where you want to set the cookie path e.g. multi App Setups under the same domain. With this PR a new env variable ```SESSION_COOKIE_PATH``` is introduced.

Introduce an env variable for the session cookie path

---

app/Config/database.php
dev/docker/entrypoint.app.sh
dev/docker/init.db/01.sql
docker-compose.yml
phpunit.xml
readme.md

This creates another mysql_testing database during db service setup
Replace server with env tags in phpunit.xml in order to force
override certain parameters when tests are run. See:
sebastianbergmann/phpunit#2353 for more
information.
Rename primary developer Docker database from bookstack-test to
bookstack-dev. bookstack-test is used as the mysql_testing database

Docker: Fix PHP tests 

---

.env.example.complete
app/Config/saml2.php

With default SAML configuration wasn't possible use Windows Authentication via AD FS and everytime is offered only login via AD FS form. That is due missing 'requestedAuthnContext' set to false  when 
IDP choose available method. Instead of that is send request with "'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport" which on AD FS force to use form.
I just use setting from onelogin/php-saml/advanced_settings and provide configuration to .ENV file

Add support Windows Authentication via SAML

---

resources/sass/_pages.scss
resources/sass/_tables.scss

PR to resolve #2732 
Tables generated by the markdown renderer don't honour the max-width property without applying word-break styling to the td elements. 
This has shown to fix the table overflow tested in Chrome, Edge, Opera, and Firefox

Fix table width styling on pages rendered in markdown

---

resources/sass/_blocks.scss
resources/views/components/tag-list.blade.php
resources/views/partials/entity-list-item-basic.blade.php
resources/views/partials/entity-list-item.blade.php
resources/views/partials/entity-list.blade.php
resources/views/search/all.blade.php

This is a basic implementation of #2462.
It's rather similar to the `$showPath` property that you can attach to any `entity-list`. Now there's another property called `$showTags` that adds all tags to the list items. I've only enabled it for the search results page, but this might come in handy in other circumstances too.
Obviously the search results link to the corresponding shelf/book/chapter/page, but the tags also contain links. This is an issue since nesting `<a>` elements is not allowed. To avoid this I've added a `$disableLinks` property to `tag-list`, which replaces the tag links with `<span>` elements.

Show tags of all search results

---

app/Auth/Access/Guards/LdapSessionGuard.php
app/Auth/Access/LdapService.php
app/Config/services.php

My BookStack instance is using Active Directory for authentication. We wanted to be able to automatically import the user photos that we already have stored in Active Directory.
This change, controlled by config values in the config/services.php file, allows for user avatars to be imported from the LDAP thumbnailPhoto attribute. Users can still update their images from the profile page.

Import thumbnail photos when LDAP users are created.

---

resources/views/api-docs/index.blade.php
resources/views/attachments/manager-list.blade.php
resources/views/common/footer.blade.php
resources/views/components/image-manager-form.blade.php
resources/views/components/page-picker.blade.php
resources/views/pages/revisions.blade.php
resources/views/partials/entity-export-menu.blade.php

Using `target="_blank"` on links without adding `rel="noopener"` can be a minor vulnerability. 
See [RSPEC-5148](https://rules.sonarsource.com/html/RSPEC-5148) for more info on the specifics of the issue.
This is not really an issue on most up to date browsers (Chrome 88+, Firefox 79+ or Safari 12.1+) though I think its always best to program defensively since you don't know what browser the end users will end up using. 
If you don't see any benefit in adding this feel free to close.

[sec] Fixes a few minor vulnerabilies when using target="_blank" on links (RSPEC-5148)

---

app/Entities/Models/Page.php
app/Entities/Repos/PageRepo.php
app/Http/Controllers/PageController.php
resources/sass/_layout.scss
resources/sass/_text.scss
resources/views/pages/show.blade.php

- Added feature to navigate through the different pages.
- This will help the user to navigate through different pages without scrolling above and clicking on the page.
- User can directly switch to the next page from the bottom of the page.
- This feature will be more helpful if the user using mobile/tab then, the user doesn't have to switch to the info tab from the content tab to view the next page.
- After the implementation of this feature user can view the next or previous page without switching to the info tab from the content tab.
Prev and Next button functionality can be seen in the attached video below:
https://user-images.githubusercontent.com/57482557/105948778-98804680-6091-11eb-9eff-893d7b3482e6.mp4

Add prev and next button to navigate through different pages

---

app/Entities/Tools/PageContent.php

**Overview**
This allows usage of base64 image blobs in pages by parsing them from posts during submission and saving them as images. This ties almost entirely into existing code.
Based on our discussion in #2631, I think this solution would be preferable.
**Benefits**
Even if this exact pull request isn't accepted, a solution with this design has many benefits.
- Avoids storing images as text blobs in the database, instead saving them as native BookStack images.
- Integrated directly into BookStock rather than tied to WYSIWYG editors, which could change in the future.
- Allows importing image data via the API. Export formats from knowledge systems (including BookStack's own) often use base64 image blobs. Importing with them with the API is currently more difficult than necessary.
- …

Add base64 image blob support

---

app/Entities/ExportService.php
app/Http/Controllers/BookExportController.php
app/Http/Controllers/ChapterExportController.php
app/Http/Controllers/PageExportController.php
composer.json
composer.lock
dev/docker/Dockerfile
resources/lang/en/entities.php
resources/views/partials/entity-export-menu.blade.php
routes/web.php

I want to be able to export a full, organized, plaintext copy of a book like @XVilka [suggests](https://github.com/BookStackApp/BookStack/issues/1717#issuecomment-543028773) in #1717.
I know this is a cold PR, but hopefully there's something usable in here. General guidance for how/where to implement these features is appreciated.
These are things that might be good to also add... not sure where to start on them though.
- Adopting BookStack is easier knowing that all the data stored there is in a standard format. 
- A lot of people like git sync (hi @dkess), so this makes that possible with external software.

Markdown Export

---

resources/lang/en/settings.php
resources/views/settings/recycle-bin/index.blade.php

According to issue #2594 when a child item has been deleted and the parent item also gets deleted, there is no way to see the parent information in order to recover child item. This PR includes parent information in recycle bin to help user recover child elements.

Including parent information in recycle bin

---

app/Entities/Tools/PageEditActivity.php
app/Http/Controllers/PageController.php
resources/js/components/page-editor.js

Currently, warnings are displayed if two users are editing the same page at the same moment. More precisely, a warning is displayed if a second user starts editing a page when a first user has already opened the editor AND saved a first draft. If those two people open the page at the same moment (thus no draft is saved yet), they get no warning.
This patch adds a warning each time a draft is saved, when several users are editing the same page (with a draft already saved for each of them) or when the edited draft is older than the last page version.

Concurrent page editing: more warnings

---

app/Actions/Tag.php
app/Console/Commands/RegenerateSearch.php
app/Entities/Models/Book.php
app/Entities/Models/Bookshelf.php
app/Entities/Models/Chapter.php
app/Entities/Models/Entity.php
app/Entities/Models/Page.php
app/Entities/Repos/PageRepo.php
app/Entities/Tools/SearchIndex.php
app/Entities/Tools/SearchOptions.php
app/Entities/Tools/SearchResultsFormatter.php
app/Entities/Tools/SearchRunner.php
app/Http/Controllers/SearchController.php
database/seeders/LargeContentSeeder.php
resources/sass/_blocks.scss
resources/views/entities/list-item-basic.blade.php
resources/views/entities/list-item.blade.php
resources/views/entities/tag.blade.php
tests/Entity/EntitySearchTest.php

This PR tracks ideas and progress for a series of improvements to be made for the search system.
- **Term relative frequency based ranking**
- Related: #2894,  #2840
- _Adjust search scores based on the relative use of the given terms so that a common word has a lesser impact on search score compared to a relatively rarely-used word._
- **Adjust existing scoring to boost titles/names further**
- Related:  #2840
- **Content parsing for heading boosting**
- _Boost terms used in header formats (h1, h2, h3...). Will need to see if performance hit from parsing is viable, Including when doing a system-re-index operation. (Maybe add a progress bar?)_
- **Match tags for standard terms**
- Related:  #1577
- _Include tag names and values as indexed search terms so that they can be search without …

Search Engine Improvement

---

resources/views/mfa/parts/verify-totp.blade.php

Adding tabindex=0 means when pressing tab the focus goes right to the TOTP input field.  When using a Password Manager this makes it easier than having to hit tab 3X to get the right focus.

Set taborder for TOTP Verification

---

app/Console/Kernel.php
app/Theming/ThemeService.php
dev/docs/logical-theme-system.md
tests/ThemeTest.php

Added initial work to support registering commands through the logical
theme system. Includes docs changes and example.
Related to #2288

Support custom commands via logical theme system

---

app/Entities/Tools/PageContent.php
app/Entities/Tools/SearchResultsFormatter.php

When a search is made, the information that is shown in every result snippet is taken from database tables 'bookshelves', 'books', 'chapters', 'pages', but the string data in them may be encoded in format different than one-to-one byte format. For example for every cyrillic character are used up to four bytes for representation.
Operations on strings in this context are not multi-byte safe and the returned snippets contain 'broken' information.
I think the multibyte string methods are a good alternative for the solution of that problem.

Make building of search results work for multi-byte encoded characters

---

app/Http/Controllers/AuditLogController.php
database/migrations/2021_11_26_070438_add_index_for_user_ip.php
resources/lang/en/settings.php
resources/views/settings/audit.blade.php
tests/AuditLogTest.php

Features:
- add input field for searching IP address in audit log view.
- add a hidden submit button in view. Form submits automatically after user press `Enter`
- add search type in audit log controller. IP address search in full string match. (use `=` not `like`)
- create index for user ip address (DB migration)
UI preview :
----
Note: related with issue #2951

Search by User IP Adress in Audit Log

---

app/Entities/Models/Chapter.php
app/Entities/Repos/ChapterRepo.php
app/Entities/Repos/PageRepo.php
app/Entities/Tools/Cloner.php
app/Facades/Activity.php
app/Http/Controllers/BookController.php
app/Http/Controllers/ChapterController.php
app/Http/Controllers/PageController.php
app/Http/Controllers/RoleController.php
resources/lang/en/entities.php
resources/views/books/copy.blade.php
resources/views/books/show.blade.php
resources/views/chapters/copy.blade.php
resources/views/chapters/show.blade.php
resources/views/entities/copy-considerations.blade.php
resources/views/pages/copy.blade.php
resources/views/settings/roles/create.blade.php
resources/views/settings/roles/edit.blade.php
resources/views/settings/roles/parts/form.blade.php
routes/web.php
tests/Entity/BookTest.php
tests/Entity/ChapterTest.php
tests/Permissions/RolesTest.php

As per definition at https://github.com/BookStackApp/BookStack/issues/1123#issuecomment-997232636.
- Permissions will not be copied. 
- Page Attachments will not be copied.
- Page images will not be updated nor will their relation to pages be updated.
- Copied content owner will be the copier.
- Due to the above, copied content could be visible to a different set of people. 
---
Related to #1123

Additional copy/clone abilities

---

app/Http/Controllers/PageController.php
resources/views/entities/list-item.blade.php

See https://github.com/BookStackApp/BookStack/issues/3045 for informations

enh(recently updated): show updatedBy and updated_at

---

readme.md

In the rich diff, one can see that some of the images are still broken:
Codeberg returns an error 500 for these.

Update sponsor image URLs in readme
